# services:
#   flask:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: api
#     ports:
#       - "5000:5000"
#     environment:
#       DB_HOST: ${DB_HOST}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       DB_NAME: ${DB_NAME}
#       DB_PORT: ${DB_PORT}
#       UPLOAD_DIR: /app/uploads
#     volumes:
#       - ./uploads:/app/uploads
#     depends_on:
#       - mysql
#     env_file:
#       - .env
#     networks:
#       - app-network

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     env_file:
#       - .env
#     networks:
#       - app-network

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

# volumes:
#   mysql_data:

networks:
  app-network:
    driver: bridge
